version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: ["npm", "run", "dev", "--", "--host", "--port", "5173"]

  crawler:
    build:
      context: ./src/components/layout/notice
      dockerfile: Dockerfile-crawler
    volumes:
      - ./src/components/layout/notice:/app
    command: ["python", "notice_crawler.py"]

## 실행 방법
# cd Nest-FE
# docker-compose up --build
## React 프론트 서버: localhost:5173 에서 열림
## Python 크롤러: notice_crawler.py 자동 실행됨
## (예: 크롤링해서 MySQL 저장 or 파일 저장)