# ✅ Python 3.12 슬림 버전 사용
FROM python:3.12-slim

# # ✅ 필요한 패키지 설치 (크롬, 크롬드라이버 포함)
# RUN apt-get update && apt-get install -y \
#     wget \
#     curl \
#     unzip \
#     gnupg \
#     ca-certificates \
#     fonts-liberation \
#     libasound2 \
#     libatk-bridge2.0-0 \
#     libatk1.0-0 \
#     libcups2 \
#     libdbus-1-3 \
#     libgdk-pixbuf2.0-0 \
#     libnspr4 \
#     libnss3 \
#     libx11-xcb1 \
#     libxcomposite1 \
#     libxdamage1 \
#     libxrandr2 \
#     xdg-utils \
#     --no-install-recommends && \
#     rm -rf /var/lib/apt/lists/*

# # ✅ 크롬 설치
# RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
# RUN echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
# RUN apt-get update && apt-get install -y google-chrome-stable

# ✅ 프로젝트 코드 복사
WORKDIR /app
COPY . .

# ✅ Python 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# ✅ 포트 오픈
EXPOSE 8000

# ✅ 서버 실행
CMD ["uvicorn", "notice_crawler:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
