// src/constants/mock-projects.ts
export const mockProjects = [
  {
    id: 28,
    title: "[팀원 모집] 2025 광주 AI 해커톤 인원 모집합니다! 프론트1, 백1 구해요",
    date: "2025.01.02",
    author: "도레미",
    views: 20,
    participants: "3/6",
    hasAttachment: true,
  },
  {
    id: 27,
    title: "[팀원 모집] 기초프로그래밍 멘토 구합니다",
    date: "2025.01.02",
    author: "홍길동",
    views: 51,
    participants: "1/5",
    hasAttachment: false,
  },
  {
    id: 26,
    title: "[스터디 모집] 같이 Unity 공부하실 분~?",
    date: "2025.01.03",
    author: "김나리",
    views: 38,
    participants: "7/10",
    hasAttachment: true,
  },
  {
    id: 25,
    title: "기획자 되고 싶은 사람 모여라",
    date: "2025.01.04",
    author: "문성훈",
    views: 43,
    participants: "8/8",
    hasAttachment: false,
  },
  {
    id: 24,
    title: "[스터디 모집] 정보처리기사 같이 취득해요",
    date: "2025.01.05",
    author: "이철수",
    views: 55,
    participants: "1/5",
    hasAttachment: false,
  },
  {
    id: 23,
    title: "백엔드 프로젝트 인원 구해요",
    date: "2025.01.06",
    author: "이사람",
    views: 100,
    participants: "2/5",
    hasAttachment: true,
  },
  {
    id: 22,
    title: "프론트엔드 프로젝트 인원 구해요",
    date: "2025.01.07",
    author: "홍길동",
    views: 100,
    participants: "4/5",
    hasAttachment: false,
  },
  {
    id: 21,
    title: "[팀 프로젝트] 공공데이터 기반 앱 제작 같이 하실 분",
    date: "2025.01.08",
    author: "박유진",
    views: 89,
    participants: "5/6",
    hasAttachment: true,
  },
];