# Port Number
server:
  port: 6030 # Conflict occurred with Tomcat in JSP...ㅠㅠ

# mysql -h 119.219.30.209 -P 6040 -u VIRTUKCH -p --default-character-set=utf8 nest_db
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/nest_db?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:VIRTUKCH}
    password: ${DB_PASSWORD:VIRTUKCH}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:glosori.help@gmail.com}
    password: ${MAIL_PASSWORD:jzdschbukjgnjffz}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    default-encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: ${JPA_SHOW_SQL:true}

jwt:
  secret: ${JWT_SECRET:VUkwMS0xMjM0LTU2NzgtOWFiYy1kZWZnaGk=}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}  # 1 hour (in milliseconds)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}  # 7 days (in milliseconds)

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    csrf:
      enabled: false  # ✅ CSRF 설정이 Swagger 요청을 차단할 수 있으므로 비활성화